config/routes.rb
Rails.application.routes.draw do
  resources :books
  resources :tasks do
    member do
      put :complete
    end
  end
  resources :user
  root 'pages#home'

  get 'signup'    => 'pages#signup'
  post 'signin'   => 'sessions#signin'
  delete 'signout'  => 'sessions#signout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\-.]+\.[a-z]+\z/i
  validates :name, presence: true, length: {maximum: 50}
  validates :email, presence: true, length: {maximum: 255},
                    format: {with: VALID_EMAIL_REGEX},
                    uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: {minimum: 8}
  
  has_many :task, -> { order(created_at: :DESC)}
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  include ApplicationHelper

  def logged_in?
    if !session[:current_user_id]
      redirect_to root_path and return
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
    @user = current_user
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
    @user = current_user
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
      @user = current_user
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:user_id, :title, :image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :logged_in?, only: %i[ home signup ]
  layout 'home'

  def home
  end

  def signup
  end

  private

  def logged_in?
    if session[:current_user_id]
      redirect_to tasks_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def signin
    @user = User.where(email: params[:email]).first
    if @user&.authenticate(params[:password])
      redirect_to root_path, flash: {error: 'Email or Password do not match!'} and return
    end
    session[:current_user_id] = @user.id
    redirect_to tasks_path
  end

  def signout
    reset_session
    redirect_to root_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :logged_in?, :set_task, only: %i[ show edit update destroy complete]
  
  def index
    @pagy, @tasks = pagy(User.find(session[:current_user_id]).task, items: 10)
    @user = current_user
  end

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = Task.new(set_user_id(task_params))
    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_url, notice: "Task was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_url, notice: "Task was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
    end
  end

  def complete
    respond_to do |format|
      if @task.update_attribute(:status, true)
        format.html { redirect_to tasks_url, notice: "Task was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  private

    def set_task
      @task = Task.find(params[:id])
      @user = current_user
    end

    def task_params
      params.require(:task).permit(:description)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :logged_in?, only: %i[ show update edit ]
  before_action :set_user, only: %i[ edit update]

  def index
    render json: User.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, flash: {notice: "Account created for #{params[:email]}"}
    else
      redirect_to signup_path, flash: {error: "Error creating an account"}
    end
  end

  def show
  end
  
  def update
    respond_to do |format|
      if @user.update(user_update_params)
        format.html { redirect_to edit_user_path(@user), flash: {notice: "Update successful!"} }
      else
        format.html { redirect_to edit_user_path(@user), flash: {notice: "Update failed!"} }
      end
    end
  end
  
  def edit
  end
  
  private

  def user_params
    params.permit(:name, :email, :password, :password_confirmation)
  end

  def user_update_params
    params.require(:user).permit(:name, :email, :image)
  end

  def set_user
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
  include UserHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper

  def set_user_id(task_params)
    task_params[:user_id] = session[:current_user_id]
    task_params
  end
end

app/helpers/user_helper.rb
module UserHelper

  def current_user
    if (user_id = session[:current_user_id])
      @current_user ||= User.find_by(id: user_id)
    end
  end
end

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="col-md-6 mt-5">
    <%= form_with model: @book do |form| %>
        <div class="form-group mb-2">
            <% if @book.image.attached? %>
              <%= image_tag @book.image, :class => 'img w-50' %>
            <% end %>
            <%= form.label :image %><br>
            <%= form.file_field :image %>
        </div>
        <div class="form-group mb-2">
            <%= form.label :user_id %>
            <%= form.text_field :user_id, :class => 'form-control' %>
        </div>
        <div class="form-group mb-2">
            <%= form.label :title %>
            <%= form.text_field :title, :class => 'form-control' %>
        </div>
        <%= form.submit :class => 'btn btn-primary' %>
    </div>
<% end %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.user_id %></td>
        <td><%= book.title %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @book.user_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand">Todo</a>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="<%= edit_user_path(@user) %>">Profile</a>
            </li>
        </ul>
    </div>
    <form class="form-inline" action="<%= signout_path %>" method="DELETE">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <input class="form-control mr-sm-2" type="submit" value="Sign Out" aria-label="Sign Out">
    </form>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
        <div class="row d-flex justify-content-center">
            <p id="notice"><%= notice %></p>
            <%= yield %>
        </div>
    </div>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="row d-flex justify-content-center mt-5">
    <div class="col-md-4">
        <p id="error"><%= flash[:error] %></p>
        <p id="notice"><%= flash[:notice] %></p>
        <form class="form-signin" method="POST" action="signin">
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <h1 class="h3 mb-3 font-weight-normal">Login</h1>
            <div class="form-group">
                <label for="email" class="sr-only">Email address</label>
                <input type="email" name="email" id="email" class="form-control" placeholder="Email address" required autofocus>
            </div>
            <div class="form-group">
                <label for="password" class="sr-only">Password</label>
                <input type="password" name="password" id="password" class="form-control" placeholder="Password" required>
            </div>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
            <p class="mt-5 mb-3 text-muted">Don't have an account? <a href="/signup">Signup here.</a></p>
        </form>
    </div>
</div>

app/views/pages/signup.html.erb
<div class="row d-flex justify-content-center mt-5">
    <div class="col-md-4">
        <p id="error"><%= flash[:error] %></p>
        <p id="notice"><%= flash[:notice] %></p>
        <form class="form-signin" action="/user" method="POST">
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <h1 class="h3 mb-3 font-weight-normal">Signup</h1>
            <div class="form-group">
                <label for="name" class="sr-only">Name</label>
                <input type="text" name="name" id="name" class="form-control" placeholder="Name" required autofocus>
            </div>
            <div class="form-group">
                <label for="email" class="sr-only">Email address</label>
                <input type="email" name="email" id="email" class="form-control" placeholder="Email address" required>
            </div>
            <div class="form-group">
                <label for="password" class="sr-only">Password</label>
                <input type="password" name="password" id="password" class="form-control" placeholder="Password" required>
            </div>
            <div class="form-group">
                <label for="password_confirmation" class="sr-only">Password Confirmation</label>
                <input type="password" name="password_confirmation" id="password_confirmation"
                class="form-control" placeholder="Password Confirmation" required>
            </div>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
            <p class="mt-5 mb-3 text-muted">Already have an account? <a href="/">Sign In.</a></p>
        </form>
    </div>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="col-md-4">
    <form action="/tasks/<%= @task.id %>" method="POST">
        <%= hidden_field_tag :_method, 'patch' %>
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <h1>New Task</h1>
        <div class="form-group">
            <label for="description">Description</label>
            <input type="text" name="task[description]" class="form-control" value="<%= @task.description %>" required>
        </div>
        <div class="row d-flex justify-content-between w-100">
            <a href="<%= tasks_path %>" class="btn btn-secondary btn-sm">Back</a>
            <button class="btn btn-primary btn-sm">Update</button>
        </div>
    </form>
</div>

app/views/tasks/index.html.erb
<div class="col-md-6">
    <h1>Tasks</h1>
    <a href="<%= new_task_path  %>" class="btn btn-primary mb-2">New</a>

    <ul class="list-group">
        <% @tasks.each do |task| %>
            <li class="list-group-item  d-flex justify-content-between align-items-center">
                <% if task.status %>
                    <del><%= task.description %></del>
                <% else %>
                    <div class="row d-flex justify-content-between w-75">
                        <span class="h6 ml-3"><%= task.description %></span>
                        <span><%= time_ago_in_words(task.created_at) %> ago</span>
                    </div>
                <% end %>
                
                <span>
                    <% if !task.status %>
                        <%= link_to "Complete", complete_task_path(task), method: :put %>
                    <% end %>
                    <%= link_to 'Edit', edit_task_path(task) %>
                    <%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %>
                </span>
            </li>
        <% end %>
    </ul>
    <br>
    <%== pagy_bootstrap_nav(@pagy)%>        
</div>

app/views/tasks/new.html.erb
<div class="col-md-4">
    <form action="<%= tasks_path %>" method="POST">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <h1>New Task</h1>
        <div class="form-group">
            <label for="description">Description</label>
            <input type="text" name="task[description]" class="form-control" required autofocus>
        </div>
        <div class="row d-flex justify-content-between">
            <a href="<%= tasks_path %>" class="btn btn-secondary">Back</a>
            <button class="btn btn-primary">Create</button>
        </div>
    </form>
</div>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @task.user_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/user/edit.html.erb
<div class="col-md-6 mt-5">
    <%= form_with model: @user do |form| %>
        <div class="form-group mb-2">
            <% if @user.image.attached? %>
              <%= image_tag @user.image, :class => 'avatar' %>
            <% end %>
            <%= form.label :image %><br>
            <%= form.file_field :image %>
        </div>
        <div class="form-group mb-2">
            <%= form.label :name %>
            <%= form.text_field :name, :class => 'form-control' %>
        </div>
        <div class="form-group mb-2">
            <%= form.label :email %>
            <%= form.text_field :email, :class => 'form-control' %>
        </div>
        <%= form.submit :class => 'btn btn-primary' %>
    </div>
<% end %>

app/views/user/index.html.erb
hi

app/views/user/update.html.erb
<h1>User#update</h1>
<p>Find me in app/views/user/update.html.erb</p>